### PR TITLE
Implementing issue #2; use SinonJS to improve unit test readability

### PR DESCRIPTION
**Pull request by JohnnyEstilles**
Implementing issue #2.
Unit tests still need some work, but this is a good start.

### CODE REVIEW

**Comment by pinoyyid** [comment]
Question about how failures appear in karma log output:
In my original, `expect('should have failed D251 no fileId').toBe('false')` would fail with a message containing "should have failed D251 no fileId". Am I correct that with sinon, it would fail with "success should not have been called" (or similar). If so, given that some `it`' contain multiple expects, how would one identify the individual expect that is failing?

**Comment by JohnnyEstilles** [comment]
@pinoyyid, that is actually what one of the issues to which I was referring when I wrote "Unit tests still need some work, but this is a good start."

> Am I correct that with sinon, it would fail with "success should not have been called" (or similar).

Yes, you are correct.

> If so, given that some it' contain multiple expects, how would one identify the individual expect that is failing?

Each test (i.e. `it('...')`) should test only one concern. Some of your tests need to be segregated. I will gladly separate them and push another commit to these PR.

**Comment by pinoyyid** [comment]
I confess that where concerns are trivial and closely related, I tend to aggregate them. If there is no mechanism to add a descriptive message to the logged failure message, then you're right that the concerns will need to be segregated before we merge them to avoid ambiguous log messages.

**Comment by JohnnyEstilles** [comment]
I agree, the do seem extremely closely related, but technically they are distinct tests. I will separate them for you and push another commit.

**Comment by JohnnyEstilles** [comment]
I've reorganized, not only the tests in question, but all the tests to be more descriptive upon failure.

**Comment by pinoyyid** [comment]
very nice

**Comment by JohnnyEstilles** [comment]
Thanks! My pleasure.

**Pull request merged**
