### PR TITLE
Fixing Issue #1; remove node_modules.tar.gz and untrack bower_components

### PR DESCRIPTION
**Pull request by JohnnyEstilles**
Fixing issue #1

This PR includes the following:
- updated package.json with all current Node dependencies
- removed node_modules.tar.gz 
- karma config cleanup
- grunt file cleanup
- updated cloning/hacking instructions

### CODE REVIEW

**Comment by JohnnyEstilles** [comment]
@pinoyyid, once you merge this into `master` you can/should merge into your `dev` branch as well. For good measure, you should remove `node_modules` and reinstall Node all dependencies using `npm install`. You could do the same with the Bower dependencies, but it shouldn't be necessary.

**Comment by pinoyyid** [comment]
Done. I also moved bower down into each of the two directories as the nggapi_lib "app" has minimal bower requirements, whereas I expect demo-app to have more.

**Comment by JohnnyEstilles** [comment]
@pinoyyid, I noticed you physically moved the `bower.json` file. FYI ... the standard practice is to leave the `bower.json` file in the root of the project, and use the `.bowerrc` for to indicate the location into which the bower components will be installed.

You should return `bower.json` to to project root, then change `.bowerrc` to:

```js
{
  "directory": "nggapi_lib\bower_components"
}
```

**Comment by pinoyyid** [comment]
Thx for the tip. I'll leave it as is that for the moment. The repo has two apps. The library proper is in `nggapi_lib` which contains a minimal HTML app for development and simple testing purposes. `demo-app` is intended to a full Drive CRUD type of application that makes use of the library, and so will have different bower requirements. Given the lack of progress on demo-app, I'm considering removing it from the repo completely, at which point I'll implement your tip. If demo-app remains, then the "main" bower will be used for that app.

**Pull request merged**
